config/routes.rb
Rails.application.routes.draw do
  resources :pois
  resources :bookmarks, only: [:index, :create, :show, :destroy]

  get "/contact", to: "contact#new"
  post "/contact", to: "contact#create"

  devise_for :users

  root to: 'home#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/poi.rb
##
# Defines the Poi (point of interest) model. Pois have the following attributes:
#
# +name+::  string
# +rating+::  int
# +website+::  string
# +price+::  string
# +description+::  string
# +category+::  enum (int)
# +lat+::  string
# +lon+::  string
# +public+::  boolean
# +featured+::  boolean
# +owner_id+::  foreign key (+Users+ model)
#
class Poi < ApplicationRecord
  belongs_to :owner, class_name: "User"
  
  enum category: [:restaurant, :nature, :museum, :nightlife, :outdoor_activity, :shopping, :landmark]

  validates :name, :owner, :category, presence: true
  validates :website, url: true
  validates :rating, numericality: { greater_than_or_equal_to: 1,
                                     less_than_or_equal_to: 5 },
                     allow_nil: true
  validates :lat, numericality: { greater_than_or_equal_to: -90,
                                  less_than_or_equal_to: 90 },
                  allow_nil: true
  validates :lon, numericality: { greater_than_or_equal_to: -180,
                                  less_than_or_equal_to: 180 },
                  allow_nil: true
  
  has_many :bookmarks, dependent: :destroy
  attribute :featured, :boolean, default: false
end

app/controllers/pois_controller.rb
##
# Actions for the POIs resource
class PoisController < ApplicationController
  include Authorization

  before_action :authenticate_user!, only: [:index, :new, :edit, :create, :update, :destroy]
  before_action :set_poi, only: [:show, :edit, :update, :destroy]
  before_action :allow_if_owner!, only: [:edit, :update, :destroy]

  # GET /pois
  # GET /pois.json
  def index
    @t_scope = [:pois, :index]
    @my_pois = Poi.where(owner: current_user)
    if current_user.admin?
      @other_pois = Poi.where.not(owner: current_user)
    end
  end

  # GET /pois/1
  # GET /pois/1.json
  def show
    unless @poi.public? || @poi.owner == current_user || current_user.admin? 
      deny_access!
    end

    @t_scope = [:pois, :show]
    @title = @poi.name
    
    @bookmark =
      if current_user.present?
        Bookmark.find_by(owner: current_user, poi: @poi)
      else
        nil
      end
  end

  # GET /pois/new
  def new
    @t_scope = [:pois, :new]
    @poi = Poi.new
  end

  # GET /pois/1/edit
  def edit
    @t_scope = [:pois, :edit]
  end

  # POST /pois
  # POST /pois.json
  def create
    @poi = Poi.new(poi_params)
    @poi.owner = current_user

    respond_to do |format|
      if @poi.save
        format.html { redirect_to @poi, notice: t('create_success', scope: :pois) }
        format.json { render :show, status: :created, location: @poi }
      else
        format.html { render :new }
        format.json { render json: @poi.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pois/1
  # PATCH/PUT /pois/1.json
  def update
    respond_to do |format|
      if @poi.update(poi_params)
        format.html { redirect_to @poi, notice: t('update_success', scope: :pois) }
        format.json { render :show, status: :ok, location: @poi }
      else
        format.html { render :edit }
        format.json { render json: @poi.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pois/1
  # DELETE /pois/1.json
  def destroy
    @poi.destroy
    respond_to do |format|
      format.html { redirect_to pois_path, notice: t('destroy_success', scope: :pois) }
      format.json { head :no_content }
    end
  end

  private

    ##
    # Sets the POI from the ID passed as a parameter to the route
    def set_poi
      @poi = Poi.find(params[:id])
    end

    ##
    # Defines which parameters should be accepted
    def poi_params
      permitted_params = [:public, :name, :rating, :website, :price, :description, :category, :lat, :lon]

      # Only allow admins to change the featured field
      permitted_params.push :featured if current_user.admin?

      params.require(:poi).permit(permitted_params)
    end
end

app/helpers/pois_helper.rb
module PoisHelper
end

app/views/pois/_admin-index.html.erb
<% if current_user.admin? %>
  <h2><%= t('admin.heading', scope: @t_scope) %></h2>

  <% if @other_pois && @other_pois.count > 0 %>
    <table>
      <thead>
        <tr>
          <th><%= t('admin.name', scope: @t_scope) %></th>
          <th><%= t('admin.category', scope: @t_scope) %></th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @other_pois.each do |poi| %>
          <tr>
            <td><%= poi.name %></td>
            <td><%= poi.category.humanize %></td>
            <td><%= link_to t('admin.show', scope: @t_scope), poi %></td>
            <% if current_user == poi.owner || current_user.admin? %>
              <td><%= link_to t('admin.edit', scope: @t_scope), edit_poi_path(poi) %></td>
              <td><%= link_to t('admin.destroy', scope: @t_scope), poi, method: :delete,
                      data: { confirm: t('admin.destroy_confirm', scope: @t_scope) } %></td>
            <% end %>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% else %>
    <p><em><%= t('admin.empty', scope: @t_scope) %></em></p>
  <% end %>
<% end %>

app/views/pois/_form.html.erb
<% @ft_scope = [:pois, :form] %>
<%= form_with(model: poi, local: true) do |form| %>
  <% if poi.errors.any? %>
    <div>
      <p><strong><%= t('error_count', scope: @ft_scope, count: poi.errors.count) %> <%= t('error_msg', scope: @ft_scope) %></strong></p>

      <ul>
      <% poi.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :category, t('category', scope: @ft_scope) %>
    <%= form.select :category, Poi.categories.collect {|name, id| [ name.humanize, name ] } %>
  </div>

  <div class="field">
    <%= form.label :name, t('name', scope: @ft_scope) %>
    <%= form.text_field :name %>
  </div>

  <div class="field-row">
    <div class="field">
      <%= form.label :lat, t('latitude', scope: @ft_scope) %>
      <%= form.text_field :lat %>
    </div>

    <div class="field">
      <%= form.label :lon, t('longitude', scope: @ft_scope) %>
      <%= form.text_field :lon %>
    </div>
  </div>

  <div class="field">
    <%= form.label :website, t('website', scope: @ft_scope) %>
    <%= form.text_field :website %>
  </div>

  <div class="field">
    <%= form.label :price, t('price', scope: @ft_scope) %>
    <%= form.text_field :price %>
  </div>

  <div class="field">
    <%= form.label :description, t('description', scope: @ft_scope) %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :rating, t('rating', scope: @ft_scope) %>
    <%= form.number_field :rating, min: 1, max: 5 %>
  </div>

  <div class="field --switch">
    <%= form.label :public, t('public', scope: @ft_scope) %>
    <%= form.check_box :public %>
    <label for="poi_public" class="field_toggle"></label>
  </div>

  <% if current_user.admin? %>
    <div class="field --switch">
      <%= form.label :featured, t('featured', scope: @ft_scope) %>
      <%= form.check_box :featured %>
      <label for="poi_featured" class="field_toggle"></label>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit t('submit', scope: @ft_scope), class: "button" %>
    <%= link_to t('cancel', scope: @ft_scope), pois_path %>
  </div>
<% end %>

app/views/pois/edit.html.erb
<h1><%= t('title', scope: @t_scope) %></h1>

<%= render 'form', poi: @poi %>

app/views/pois/index.html.erb
<h1><%= t('title', scope: @t_scope) %></h1>

<%= link_to t('new', scope: @t_scope), new_poi_path %>

<% if @my_pois.count > 0 %>
  <%= render "shared/poi-listing", pois: @my_pois %>
<% else %>
  <p><em><%= t('empty', scope: @t_scope) %></em></p>
<% end %>

<%= render "admin-index" %>

app/views/pois/new.html.erb
<h1><%= t('title', scope: @t_scope) %></h1>

<%= render 'form', poi: @poi %>

app/views/pois/show.html.erb
<script>
  $.onmount('[data-js-map]', function () {
    centerOnMarker(<%= @poi.id %>);
  });
</script>

<header class="poi-header">
  <h1 class="poi-header_heading">
    <span class="poi-header_category"><%= @poi.category.humanize %></span>
    <span class="poi-header_separator">:</span>
    <span class="poi-header_name"><%= @poi.name %></span>
  </h1>
  <% if @bookmark %>
    <%= link_to bookmark_path(@bookmark.id), method: :delete, title: t('unmark_alt', scope: @t_scope), class: "poi-header_bookmark --marked" do %>
      <svg class="sprite --bookmark" aria-label="<%= t('unmark_alt', scope: @t_scope) %>">
        <use xlink:href="/assets/sprite.svg#bookmark_marked"></use>
      </svg>
    <% end %>
  <% else %>
    <%= link_to bookmarks_path(:"bookmark[poi_id]" => @poi.id), method: :post, title: t('mark_alt', scope: @t_scope), class: "poi-header_bookmark --unmarked" do %>
      <svg class="sprite --bookmark" aria-label="<%= t('mark_alt', scope: @t_scope) %>">
        <use xlink:href="/assets/sprite.svg#bookmark_unmarked"></use>
      </svg>
    <% end %>
  <% end %>
</header>

<% if @poi.rating.present? %>
  <p><% @poi.rating.times do %>★<% end %></p>
<% end %>

<dl>
  <% if @poi.website.present? %>
    <dt><%= t('website', scope: @t_scope) %></dt>
    <dd><%= link_to URI.parse(@poi.website).host, @poi.website, target: "_blank" %></dd>
  <% end %>

  <% if @poi.website.present? %>
    <dt><%= t('price', scope: @t_scope) %></dt>
    <dd><%= @poi.price %></dd>
  <% end %>
</dl>

<%= simple_format(@poi.description) %>


<% if current_user && current_user.admin? %>
  <hr>

  <dl>
    <dt><%= t('owner', scope: @t_scope) %></dt>
    <dd><%= @poi.owner.email %></dd>

    <dt><%= t('public', scope: @t_scope) %></dt>
    <dd><%= @poi.public %></dd>

    <dt><%= t('featured', scope: @t_scope) %></dt>
    <dd><%= @poi.featured %></dd>
  </dl>

  <hr>
<% end %>

<div>
  <% if @poi.owner == current_user || (current_user && current_user.admin?) %>
    <%= link_to t('edit', scope: @t_scope), edit_poi_path(@poi) %> | 
  <% end %>
  <%= link_to t('back', scope: @t_scope), root_path %>
</div>