config/routes.rb
Rails.application.routes.draw do
  resources :pois
  resources :bookmarks, only: [:index, :create, :show, :destroy]

  get "/contact", to: "contact#new"
  post "/contact", to: "contact#create"

  devise_for :users

  root to: 'home#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_footer.html.erb
<footer class="site-layout_footer">
  <nav class="site-layout_nav">
    <ul>
      <li><%= link_to t('nav.home', scope: :application), root_path %></li>
      <li><%= link_to t('nav.contact', scope: :application), contact_path %></li>
      <% unless user_signed_in? %>
        <li><%= link_to t('nav.login', scope: :application), new_user_session_path %></li>
        <li><%= link_to t('nav.signup', scope: :application), new_user_registration_path %></li>
      <% else %>
        <li><%= link_to t('nav.attractions', scope: :application), pois_path %></li>
        <li><%= link_to t('nav.bookmarks', scope: :application), bookmarks_path %></li>
        <li><%= link_to t('nav.account', scope: :application), edit_user_registration_path %></li>
        <li><%= link_to t('nav.logout', scope: :application), destroy_user_session_path, method: :delete %></li>
      <% end %>
    </ul>
  </nav>
  <small class="site-layout_legal">
    <%= t('copyright', scope: :application, year: Date.current.year) %>
  </small>
</footer>

app/views/layouts/_map.html.erb
<div id="map" class="site-layout_map" data-turbolinks-permanent data-js-map></div>

<script>
  $.onmount('[data-js-map]', function () {
    resetMap();
    <% @featured_pois.each do |poi| %>
      addMarker(<%= poi.lat %>, <%= poi.lon %>, '<%= poi.category %>', <%= poi.id %>, '<%= poi.name %>');
    <% end %>
  });
</script>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>
      <% if @title %>
        <%= @title %>
      <% else %>
        <%= t('title', scope: @t_scope) %>
      <% end %>
    </title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src='https://api.mapbox.com/mapbox-gl-js/v1.4.1/mapbox-gl.js'></script>
    <link href='https://api.mapbox.com/mapbox-gl-js/v1.4.1/mapbox-gl.css' rel='stylesheet'>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link href="https://fonts.googleapis.com/css?family=Ubuntu:400,400i,500&display=swap" rel="stylesheet">
  </head>

  <body>
    <div class="site-layout">
      <%= render "layouts/map" %>

      <main class="site-layout_content" data-js-site-content>
        <header>
          <% if notice %><p class="site-layout_notice"><%= notice %></p><% end %>
          <% if alert %><p class="site-layout_alert"><%= alert %></p><% end %>
        </header>
        <div class="site-layout_content-scroll">
          <%= yield %>
        </div>
      </main>
      <div class="site-layout_content-arrow"></div>

      <%= render "layouts/footer" %>
    </div>
  </body>
</html>